# =======================[ 0. Powerlevel10k instant prompt ]===================
# Must be near the very top of ~/.zshrc.
# Change "quiet" to "off" if you want to disable instant prompt completely.
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# =======================[ 1. Basic environment ]==============================
export ZDOTDIR="$HOME"
export EDITOR="nvim"
export PATH="$HOME/.local/bin:$HOME/bin:$PATH"

# True color support for WSL/Windows Terminal
export COLORTERM=truecolor
export TERM=xterm-256color

# =======================[ 2. History ]=======================================
HISTFILE="$HOME/.zsh_history"
HISTSIZE=100000
SAVEHIST=100000

setopt HIST_IGNORE_DUPS       # don’t record duplicate commands
setopt HIST_IGNORE_SPACE      # don’t record commands starting with space
setopt HIST_VERIFY            # edit history line before running it
setopt SHARE_HISTORY          # share history between sessions
disable -p '#'
# =======================[ 3. General options ]===============================
setopt AUTO_CD                # type dir name to cd into it
setopt NO_BEEP
setopt PROMPT_SUBST
setopt INTERACTIVE_COMMENTS

# Use emacs-style keybindings (Ctrl-A/E, etc.)
bindkey -e

# =======================[ 4. Completion (fast, cached) ]=====================
autoload -Uz compinit

# store compiled completion dump in cache dir
if [[ ! -d $HOME/.cache/zsh ]]; then
  mkdir -p $HOME/.cache/zsh
fi
compinit -d $HOME/.cache/zsh/zcompdump

zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list \
  'm:{a-z}={A-Z}' \
  'r:|[._-]=* r:|=*'
zmodload zsh/complist

# =======================[ 5. FZF integration (optional) ]====================
# Will only load if installed.
[[ -f "$HOME/.fzf.zsh" ]] && source "$HOME/.fzf.zsh"

# =======================[ 6. Aliases ]=======================================
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias gs='git status -sb'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git log --oneline --graph --decorate'

alias ..='cd ..'
alias ...='cd ../..'

# =======================[ 7. Plugins ]=======================================
# Expected layout:
#   ~/.zsh/plugins/zsh-autosuggestions
#   ~/.zsh/plugins/zsh-syntax-highlighting
ZSH_PLUGIN_DIR="${ZSH_PLUGIN_DIR:-$HOME/.zsh/plugins}"

# Autosuggestions
if [[ -f "$ZSH_PLUGIN_DIR/zsh-autosuggestions/zsh-autosuggestions.zsh" ]]; then
  source "$ZSH_PLUGIN_DIR/zsh-autosuggestions/zsh-autosuggestions.zsh"
  # Make suggestions subtle; tweak or remove if you like.
  ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'
fi

# Syntax highlighting MUST be last
if [[ -f "$ZSH_PLUGIN_DIR/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]]; then
  source "$ZSH_PLUGIN_DIR/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
fi

# =======================[ 8. Powerlevel10k ]=================================
# Theme
if [[ -r "$HOME/.p10k/powerlevel10k.zsh-theme" ]]; then
  source "$HOME/.p10k/powerlevel10k.zsh-theme"
fi

# Prompt config (generated by `p10k configure`)
[[ -f "$HOME/.p10k.zsh" ]] && source "$HOME/.p10k.zsh"

# Turn off transient prompt to avoid "prompt changing" glitchiness.
typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off


# =======================[ 9. Screenshot automation ]========================
# Windows-to-WSL2 screenshot automation
# Functions are available but monitor is NOT auto-started (AHK handles it)
if [[ -f "$HOME/.config/screenshot-automation/screenshot-functions.sh" ]]; then
  source "$HOME/.config/screenshot-automation/screenshot-functions.sh"
  # Remove the dangerous 'paste' alias that overwrites clipboard
  unalias paste 2>/dev/null
fi

# bun completions
[ -s "/home/hanra/.bun/_bun" ] && source "/home/hanra/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
export PATH="$PATH:/opt/nvim-linux-x86_64/bin"
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# opencode
export PATH=$HOME/.opencode/bin:$PATH
